management:
    health:
      sentinel:
        enabled: false
    endpoint:
      health:
        show-details: always

mybatis-plus:
  global-config:
    banner: false
    db-config:
      db-type: mysql
      field-strategy: not_empty
      id-type: auto
    super-mapper-class: com.eeeffff.monitor.eklogmonitor.common.mapper.BaseMapper
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.eeeffff.monitor.eklogmonitor.dao.entity

spring:
  redis:
    database: 0
    host: 127.0.0.1
    password: 
    port: 6379
    timeout: 2000
  aop:
    auto: true
    proxy-target-class: true
  datasource:
    dynamic:
      datasource:
        master:
          username: root
          password: root
          url: jdbc:p6spy:mysql://127.0.0.1:3306/erp_metrics?useAffectedRows=true&useSSL=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          type: com.zaxxer.hikari.HikariDataSource
          initialSize: 5
          minIdle: 5
          maxActive: 20

app:
  monitor:
    es-url-list:
      - https://192.168.12.29:9200/
    es-username: elastic
    es-password: NNAYUK28t37v6qD3haHk
    dd-webhook-url: https://oapi.dingtalk.com/robot/send?access_token=
    # 往钉钉发送消息的时候有频率限制，钉钉默认每分钟最多可以发送20条
    dd-send-every-minute: 20
    # 系统执行监控的检查周期，单位为秒
    task-interval-seconds: 60
    kibana-template: http://192.168.12.29:5601/app/kibana#/discover?_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'${index}',key:query,negate:!f,type:custom,value:'${original_query}'),query:${query})),index:'${index}',interval:auto,query:(language:kuery,query:''),sort:!('@timestamp',desc))&_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'${startTime}',to:'${endTime}'))
    kibana-query-index-url: http://192.168.12.29:5601/api/saved_objects/_find?type=index-pattern&per_page=500
    # 根据部门配置需要额外接收电话告警的用户，Key为部门的ID，value的电话，多个电话以英文的逗号分隔
    phoneAlertExtraUsers:
      1 : 13255555555,13266666666,13277777777

logging:
  config: classpath:log4j2.xml
  level:
    root: info
    com.eeeffff.monitor.eklogmonitor.p6spy: info
    #org.apache.http.wire: DEBUG